# Generated by Django 4.0.3 on 2022-03-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_coin_all_time_high_coin_all_time_low'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='logo',
            field=models.URLField(null=True),
        ),
    ]
