# Generated by Django 4.0.3 on 2022-03-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_coin_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
